
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod
version="${mod_version}" #mandatory
# A display name for the mod
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''

# Mixins configuration
[[mixins]]
config="maidspell.mixins.json"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
   modId="touhou_little_maid"
   mandatory=true
   versionRange="[1.2.2,)"
   ordering="AFTER"
   side="BOTH"

[[dependencies.${mod_id}]]
    modId = "irons_spellbooks"
    mandatory = false
    versionRange = "[1.20.1-3.4.0,)"
    ordering="NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId="ars_nouveau"
    mandatory=false
    versionRange="[4.8.0,)"
    ordering="NONE"
    side="BOTH"